%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MDk6NTUiLCJsYWJlbCI6IkNvbm5lY3RlZCBub2RlcyIsIm1tZCI6ImZsb3djaGFydCBURFxuICAgIG4xW1wiTm9kZSAxXCJdXG4gICAgbjJbXCJOb2RlIDJcIl1cbiAgICBuM1tcIk5vZGUgM1wiXVxuICAgIG4xIC0tPiBuMlxuICAgIG4xIC0tPiBuMiJ9
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MDk6NTciLCJsYWJlbCI6IkNvbm5lY3RlZCBub2RlcyIsIm1tZCI6ImZsb3djaGFydCBURFxuICAgIG4xW1wiTm9kZSAxXCJdXG4gICAgbjJbXCJOb2RlIDJcIl1cbiAgICBuM1tcIk5vZGUgM1wiXVxuICAgIG4xIC0tPiBuMlxuICAgIG4xIC0tPiBuMlxuICAgIG4xIC0tPiBuMyJ9
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MTA6MDYiLCJsYWJlbCI6IkNvbm5lY3RlZCBub2RlcyIsIm1tZCI6ImZsb3djaGFydCBURFxuICAgIG4xW1wiTm9kZSAxXCJdXG4gICAgbjJbXCJOb2RlIDJcIl1cbiAgICBuM1tcIk5vZGUgM1wiXVxuICAgIG4xIC0tPiBuMlxuICAgIG4xIC0tPiBuMlxuICAgIG4yIC0tPiBuMyJ9
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MTA6MTEiLCJsYWJlbCI6IkNvbm5lY3RlZCBub2RlcyIsIm1tZCI6ImZsb3djaGFydCBURFxuICAgIG4xW1wiTm9kZSAxXCJdXG4gICAgbjJbXCJOb2RlIDJcIl1cbiAgICBuM1tcIk5vZGUgM1wiXVxuICAgIG4xIC0tPiBuMlxuICAgIG4xIC0tPiBuMlxuICAgIG4yIC0tPiBuM1xuICAgIG4zIC0tPiBuMSJ9
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MTA6MTciLCJsYWJlbCI6Ik1vdmVkIG5vZGVzIiwibW1kIjoiZmxvd2NoYXJ0IFREXG4gICAgbjFbXCJOb2RlIDFcIl1cbiAgICBuMltcIk5vZGUgMlwiXVxuICAgIG4zW1wiTm9kZSAzXCJdXG4gICAgbjEgLS0+IG4yXG4gICAgbjEgLS0+IG4yXG4gICAgbjIgLS0+IG4zXG4gICAgbjMgLS0+IG4xIn0=
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MTA6MzQiLCJsYWJlbCI6Ik1vdmVkIG5vZGVzIiwibW1kIjoiZmxvd2NoYXJ0IFREXG4gICAgbjFbXCJOb2RlIDFcIl1cbiAgICBuMltcIk5vZGUgMlwiXVxuICAgIG4zW1wiTm9kZSAzXCJdXG4gICAgbjEgLS0+IG4yXG4gICAgbjEgLS0+IG4yXG4gICAgbjIgLS0+IG4zXG4gICAgbjMgLS0+IG4xIn0=
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MTM6MTIiLCJsYWJlbCI6Ik1vdmVkIG5vZGVzIiwibW1kIjoiZmxvd2NoYXJ0IFREXG4gICAgbjFbXCJOb2RlIDFcIl1cbiAgICBuMltcIk5vZGUgMlwiXVxuICAgIG4zW1wiTm9kZSAzXCJdXG4gICAgbjEgLS0+IG4yXG4gICAgbjEgLS0+IG4yXG4gICAgbjIgLS0+IG4zXG4gICAgbjMgLS0+IG4xIn0=
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MjI6MDMiLCJsYWJlbCI6Ik1vdmVkIG5vZGVzIiwibW1kIjoiZmxvd2NoYXJ0IFREXG4gICAgbjFbXCJOb2RlIDFcIl1cbiAgICBuMltcIk5vZGUgMlwiXVxuICAgIG4zW1wiTm9kZSAzXCJdXG4gICAgbjEgLS0+IG4yXG4gICAgbjEgLS0+IG4yXG4gICAgbjIgLS0+IG4zXG4gICAgbjMgLS0+IG4xIn0=
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MjI6MjciLCJsYWJlbCI6IkFkZGVkIG5vZGUiLCJtbWQiOiJmbG93Y2hhcnQgVERcbiAgICBuMVtcIk5vZGUgMVwiXVxuICAgIG4yW1wiTm9kZSAyXCJdXG4gICAgbjNbKFwiTm9kZSAzXCIpXVxuICAgIG40WyhcIk5vZGUgNFwiKV1cbiAgICBuMSAtLT4gbjJcbiAgICBuMSAtLT4gbjJcbiAgICBuMiAtLT4gbjNcbiAgICBuMyAtLT4gbjEifQ==
%% snap:eyJ0cyI6IjIwMjYtMDctMDYgMDE6MjI6MjkiLCJsYWJlbCI6IkRlbGV0ZWQgZWxlbWVudHMiLCJtbWQiOiJmbG93Y2hhcnQgVERcbiAgICBuMVtcIk5vZGUgMVwiXVxuICAgIG4yW1wiTm9kZSAyXCJdXG4gICAgbjNbKFwiTm9kZSAzXCIpXVxuICAgIG4xIC0tPiBuMlxuICAgIG4xIC0tPiBuMlxuICAgIG4yIC0tPiBuM1xuICAgIG4zIC0tPiBuMSJ9
flowchart TD
    n1["Node 1"]
    n2["Node 2"]
    n3[("Node 3")]
    n1 --> n2
    n1 --> n2
    n2 --> n3
    n3 --> n1